### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by rkotze** [findmypast-oss/git-mob#1]
![image](https://user-images.githubusercontent.com/10452163/36455116-a2eec4fe-1696-11e8-9fdf-cb76c0542cb5.png)

It's difficult to know where this error/warning is throw and which test case is causing it.

**Comment by dideler** [comment]
Note this error doesn't print anymore since ebcab23e00fbdc39805a514f2564ae4187b7edd6, although it's not clear if it's fixed or if we're just silencing it. Need to investigate and verify before we close.

**Comment by rkotze** [comment]
Since this is fixed for the tests, I will close this. Issue #4 is similar and needs to be fixed if the git message file does not exist.
