### ISSUE TITLE
Support commits with inline message

### ISSUE THREAD

**Issue by dideler** [findmypast-oss/git-mob#22]
Commits made with the -m or --message option won't have the editor invoked, so it won't read the commit template to prepopulate the commit message. That means git mob doesn't work with this style of committing.

Committing with an inline message is discouraged for many reasons, but it's still a common practice.

It'd be surprising behaviour if you're in a mob but an inlined commit doesn't have co-authors.

**Comment by dideler** [comment]
We'd probably have to use a prepare-commit-msg hook.

**Comment by rkotze** [comment]
Yeah I agree if we ran commit with -m or --message i would expect co-author to show. 👍

**Comment by rkotze** [comment]
Since we agree on the approach, I've changed this from a question to an enhancement.

**Comment by rkotze** [comment]
Solved in release v0.4.0.
