### ISSUE TITLE
Git mob does not work in nested directories

### ISSUE THREAD

**Issue by regisbsb** [findmypast-oss/git-mob#25]

**Comment by steffinchen** [comment]
When running 'git mob' not inside the root directory of a git repo but in a subfolder, it fails with the following message: 
`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\work\github\titan\web\.git\.gitmessage'`

**Comment by rkotze** [comment]
Which version of git-mob are you using? This is fixed in the latest version.

**Comment by Sarabadu** [comment]
#28
