### ISSUE TITLE
Overide default user

### ISSUE THREAD

**Issue by Sarabadu** [findmypast-oss/git-mob#26]
will be nice an option for override the default user.

we use a common Mac for IOS and we do mob programming bus the default user is not always the same

something like
`git mob -o in1 in2 in3`

set commiter as in1 and co author as in2 and in3

**Comment by Sarabadu** [comment]
added a pull request #27

**Comment by rkotze** [comment]
Hi - Thanks for the suggestion. I do think you make a valid point of switching the main author for a shared machine.

I'd like to discuss this with @dideler about how we would like to approach this.

**Comment by Sarabadu** [comment]
Ok thanks ley me know if you nerd soñé ajust ok my request
