### ISSUE TITLE
Use a new approach for identifying authors

### ISSUE THREAD

**Issue by dideler** [findmypast-oss/git-mob#3]
We're using the same name and format for reading authors via a file like git-duet and git-pair does, i.e. `.git-authors` file. The reason we were doing this is to make the transition easier users.

But another option for easy transition is to provide a simple tool that converts the old file into a new file for git-mob. This way we aren't limited to a design which has certain drawbacks.

We won't need to use the same filename, since `.git-authors` historically also included the primary author. We could for example name it `.git-coauthors` to emphasise that it's strictly for co-authors.

We won't need to use YAML which means we can use JSON which will make git-mob commands quicker (don't need to load large third party dependencies which is very slow).

We also won't need to follow the same structure, for example, we can get rid of having multiple values on the same line (e.g. `first_name last_name; email_id`) which is confusing.

**Comment by rkotze** [comment]
I believe this issue is now fixed with release 0.1.0.
