### ISSUE TITLE
No .gitmessage file found to write to

### ISSUE THREAD

**Issue by rkotze** [findmypast-oss/git-mob#31]
![image](https://user-images.githubusercontent.com/10452163/42272295-9d6e9770-7f7d-11e8-92ef-d5b668579dd4.png)

- Git mob 0.2.2
- Git 2.10.1.windows.1
- Window 10
- Node 8.11.1

### Description

Changing author throws a error saying `no such file or directory open` and the .gitmessage file is not updated

### Steps to Reproduce

1. Command `git mob [author]`
2. Unhandled error
3. Co-authors not updated

**Expected behavior:** .gitmessage file to be updated with co-authors

**Actual behavior:** .gitmessage file **not** updated with co-authors

**Reproduces how often:** 100% of the time

**Comment by dideler** [comment]
What the current working directory when the error occurs?

**Comment by rkotze** [comment]
It is where the `.git` folder is

**Comment by rkotze** [comment]
This test fails on my change for looking for the .gitmessage file.

![image](https://user-images.githubusercontent.com/10452163/42451072-0fc47192-837e-11e8-8d81-60f46d93a47f.png)

**Comment by dideler** [comment]
Fixed in v0.2.3?

**Comment by rkotze** [comment]
I can confirm it works fine. 👍
