### ISSUE TITLE
"git mob --installTemplate" should be optional

### ISSUE THREAD

**Issue by jonsmithers** [findmypast-oss/git-mob#60]
## Summary

I don't see the point in git-mob requiring there to be a commit template if there is already a `prepare-commit-msg` hook in place.

## Motivation

To remove unnecessary configuration step for users.

## Additional context

`git mob-print` prints a very confusing/unhelpful error when the commit template is missing. This happens when you have the `prepare-commit-msg` hook installed, but haven't run `git mob --installTemplate`.

**Comment by rkotze** [comment]
Thanks for this @jonsmithers - completely agree and will get this merged in.
