### ISSUE TITLE
Support default email domain

### ISSUE THREAD

**Issue by dideler** [findmypast-oss/git-mob#9]
Users have to specify the email for every person. We could save them some keystrokes when they share the email domain (e.g. a popular public domain or coworkers).

**Comment by dideler** [comment]
Example structure

```json
{
  "coauthors": [
    "rk": {
      "name": "Richard Kotze",
      "email": "rk@findmypast.com",
     },
  ],
  "default_email_domain": "gmail.com"
}
```

**Comment by rkotze** [comment]
Part of this issue we will stop support for .git-author YAML and replace it with a json format.

**Comment by rkotze** [comment]
How about we change the .git-coauthors json format to something like:

{
  "coauthors": {
    "ad": "Amy Doe; amy@findmypast.com",
    "bd": "Bob Doe; bob@findmypast.com",
    "ja":  "Jane Anderson; janderson"
  },
  "default_email_domain": "gmail.com"
}

**Comment by dideler** [comment]
Changed focus to be on a default email address since we already support different emails.

**Comment by rkotze** [comment]
To better support default email, the `coauthors` will have a new prop `username`. This will be the first part of the email address. If this property is there then it will use the default email domain.

So the below example will output: `Richard Kotze <richard@gmail.com>`

```json
{
  "coauthors": {
    "rk": {
      "name": "Richard Kotze",
      "username": "richard"
     },
  },
  "default_email_domain": "gmail.com"
}
```

**Comment by rkotze** [comment]
My thoughts were kind of along the same lines as yours in terms of minimising confusing.

By calling a property email and saying it can also just be the first part might also be confusing. Maybe a better name is the solution?

Wikipedia about email address calls it [local-part](https://en.wikipedia.org/wiki/Email_address#Local-part). Not saying this is the prop to use, but the idea of the prop being explicit about what it does could be good.

What you're thoughts on this?

**Comment by dideler** [comment]
My thoughts are to defer this until people start asking for it 😄 

I now think of it as a minor optimisation that's not worth increasing the tool's complexity.

**Comment by rkotze** [comment]
I agree :+1:

**Comment by rkotze** [comment]
Might bring back, if requested or voted up.
